require:
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
AllCops:
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
#-------------------------------------------------------------------------------
RSpec/ExampleLength:
  Exclude:
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/person_statement_spec.rb
    - spec/unit/bods_mapping/record_processor_spec.rb
RSpec/FilePath:
  Exclude:
    - spec/register_transformer_sk.rb
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/person_statement_spec.rb
    - spec/unit/bods_mapping/record_processor_spec.rb
RSpec/MessageSpies:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/record_processor_spec.rb
RSpec/MultipleExpectations:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/person_statement_spec.rb
    - spec/unit/bods_mapping/record_processor_spec.rb
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/unit/bods_mapping/record_processor_spec.rb
RSpec/NamedSubject:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/person_statement_spec.rb
    - spec/unit/bods_mapping/record_processor_spec.rb
RSpec/StubbedMock:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/record_processor_spec.rb
RSpec/VerifiedDoubles:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/record_processor_spec.rb
