version: "3.8"
services:
  transformer-sk:
    build:
      context: .
      target: dev
    env_file: .env
    networks:
      - elasticsearch
      - redis
      - transformer
    restart: on-failure
    volumes:
      - ${DC_TRANSFORMER_SK_LIB_REGISTER_COMMON:-.dockerempty}:/home/x/lib/register-common
      - ${DC_TRANSFORMER_SK_LIB_REGISTER_SOURCES_BODS:-.dockerempty}:/home/x/lib/register-sources-bods
      - ${DC_TRANSFORMER_SK_LIB_REGISTER_SOURCES_OC:-.dockerempty}:/home/x/lib/register-sources-oc
      - ${DC_TRANSFORMER_SK_LIB_REGISTER_SOURCES_SK:-.dockerempty}:/home/x/lib/register-sources-sk
      - ./.rubocop.yml:/home/x/r/.rubocop.yml
      - ./bin:/home/x/r/bin
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./lib:/home/x/r/lib
      - ./register_transformer_sk.gemspec:/home/x/r/register_transformer_sk.gemspec
      - ./spec:/home/x/r/spec
      - ./statements:/home/x/r/statements
  redis:
    healthcheck:
      interval: 5s
      retries: 6
      start_period: 60s
      test:
        - CMD
        - redis-cli
        - PING
    image: docker.io/library/redis:7.0.5
    networks:
      - redis
    restart: on-failure
    volumes:
      - redis:/data
networks:
  elasticsearch: {}
  redis: {}
  transformer: {}
volumes:
  redis: {}
